USE USER;
SELECT * FROM USERS;

CREATE VIEW HIGH_SAL AS
SELECT * FROM USERS WHERE SALARY>60000;

SELECT * FROM HIGH_SAL;

UPDATE USERS SET SALARY=73000 WHERE ID=2;
UPDATE USERS SET SALARY=61000 WHERE NAME='Raj';
SET SQL_SAFE_UPDATES=0;

DROP VIEW HIGH_SAL;