USE USER;
SELECT * FROM USERS;

SHOW INDEXES FROM USERS;

-- SINGLE COLUMN INDEX CREATION
CREATE INDEX idx_email ON USERS(EMAIL); 

--  CREATE MULTICOLUMN INDEX
CREATE INDEX idx_gender_salary ON USERS(GENDER,SALARY); 

SELECT * FROM USERS WHERE GENDER='Female' and SALARY>70000;

DROP INDEX idx_gender_salary ON USERS;
