USE USER;

SELECT * FROM USERS;

SELECT AVG(SALARY) FROM USERS;

SELECT * FROM USERS WHERE SALARY> (SELECT AVG(SALARY) FROM USERS);

UPDATE USERS SET referred_by_id=6 WHERE id=1;
UPDATE USERS SET referred_by_id=9 WHERE id=5;

SELECT ID,NAME,REFERRED_BY_ID FROM USERS
WHERE REFERRED_BY_ID IN
(SELECT ID FROM USERS WHERE SALARY>75000);

SELECT name, salary,
(SELECT AVG(salary) FROM users) AS average_salary
FROM users;