USE USER;

SELECT GENDER,AVG(SALARY) AS AVERAGE_SALARY FROM  USERS GROUP BY GENDER;

SELECT COUNT(*) AS COUNT FROM USERS WHERE REFERRED_BY_ID IS NOT NULL;

SELECT REFERRED_BY_ID ,COUNT(*) FROM USERS WHERE REFERRED_BY_ID IS NOT NULL GROUP BY REFERRED_BY_ID;

SELECT GENDER,AVG(SALARY) AS AVG FROM USERS GROUP BY GENDER HAVING AVG(SALARY)>50000;

SELECT REFERRED_BY_ID,COUNT(*) FROM USERS WHERE REFERRED_BY_ID IS NOT NULL GROUP BY REFERRED_BY_ID HAVING
COUNT(*)>1;

SELECT GENDER,AVG(SALARY) AS AVERAGE_SALARY FROM  USERS GROUP BY GENDER WITH ROLLUP;
