USE user;

CREATE TABLE users (
    id INT ,
    name VARCHAR(100) ,
    email VARCHAR(100) NOT NULL,
    gender ENUM('Male', 'Female', 'Other'),
    date_of_birth DATE,
    salary DECIMAL(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN
);

-- ADDING  TABLE LEVEL CONSTRAINTS

ALTER TABLE USERS ADD CONSTRAINT unique_email UNIQUE (email); 
ALTER TABLE USERS ADD CONSTRAINT check_dob CHECK(date_of_birth>'2006-12-26');
ALTER TABLE USERS ADD CONSTRAINT primary_key PRIMARY KEY(id);

-- ADDING COLUMN LEVEL CONSTRAINTS
ALTER TABLE users MODIFY COLUMN name VARCHAR(100) NOT NULL;
ALTER TABLE users MODIFY COLUMN is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE users MODIFY COLUMN id INT AUTO_INCREMENT; 
ALTER TABLE USERS AUTO_INCREMENT=100;

SELECT * FROM USERS;