USE user;
ALTER TABLE USERS ADD COLUMN RAISE FLOAT;
UPDATE  USERS SET RAISE=15.6 WHERE ID=1;

SELECT * FROM users;

-- AGGREGATE FUNCTIONS
SELECT COUNT(*) AS total_count FROM users WHERE gender='Female'; 
SELECT MIN(salary) AS min_sal FROM users ;
SELECT MAX(salary) AS max_sal FROM USERS;
SELECT SUM(salary) AS TOTAL_SAL FROM USERS WHERE GENDER='Female';
SELECT gender,AVG(salary) AS avg FROM USERS GROUP BY GENDER;

-- STRING FUNCTIONS
SELECT name,LENGTH(name) AS NAME_LENGTH FROM users;
SELECT UPPER(NAME) AS UPPER_CASE FROM USERS; 
SELECT LOWER(NAME) AS LOWER_NAME FROM USERS;
SELECT CONCAT(NAME,ID,'STUD') AS REG_NO FROM USERS;

-- DATE FUNCTIONS
SELECT NOW();
SELECT CURDATE();
SELECT NAME,YEAR(DATE_OF_BIRTH) AS BIRTH_YEAR FROM USERS;
SELECT NAME,MONTH(DATE_OF_BIRTH) AS BIRTH_MONTH FROM USERS;
SELECT NAME,DAY(DATE_OF_BIRTH) AS BIRTH_DAY FROM USERS;
SELECT NAME,DATEDIFF(CURDATE(),DATE_OF_BIRTH) AS DAYS_LIVED FROM USERS; 
SELECT TIMESTAMPDIFF (YEAR,DATE_OF_BIRTH,CURDATE()) AS AGE FROM USERS WHERE ID=2;
SELECT TIMESTAMPDIFF (MONTH,DATE_OF_BIRTH,CURDATE()) AS AGE FROM USERS WHERE ID=2;
SELECT TIMESTAMPDIFF (DAY,DATE_OF_BIRTH,CURDATE()) AS AGE FROM USERS WHERE ID=2;
SELECT TIMESTAMPDIFF (HOUR,DATE_OF_BIRTH,CURDATE()) AS AGE FROM USERS WHERE ID=2;

-- MATHEMATICAL FUNCTIONS
SELECT id,ROUND(RAISE) AS ROUND_RAISE FROM USERS WHERE id=1;
SELECT ID,FLOOR(RAISE) AS FLOOR FROM USERS WHERE ID=1;
SELECT ID,CEIL(RAISE) AS CEIL FROM USERS WHERE ID=1;
SELECT NAME,MOD(SALARY,2) AS REM_SAL FROM USERS WHERE ID<5;

-- CONDITIONAL FUNCTIONS
SELECT NAME,SALARY, IF(SALARY>60000,'HIGH','LOW')  AS SAL_STATUS FROM USERS;
 


