USE USER;

-- INNER JOIN
SELECT USERS.NAME,ADDRESSES.CITY 
FROM USERS
INNER JOIN ADDRESSES ON
USERS.ID=ADDRESSES.USER_ID; 

SELECT COUNT(*) AS CITY_COUNT FROM USERS INNER JOIN ADDRESSES ON USERS.ID=ADDRESSES.USER_ID;

-- LEFT JOIN
SELECT USERS.NAME,ADDRESSES.STATE AS ADD_ST FROM USERS LEFT JOIN ADDRESSES ON USERS.ID=ADDRESSES.USER_ID;

-- RIGHT JOIN
SELECT USERS.NAME,ADDRESSES.CITY AS ADD_CITY FROM USERS RIGHT JOIN ADDRESSES ON USERS.ID=ADDRESSES.USER_ID;  

ALTER TABLE users
ADD COLUMN referred_by_id INT;
UPDATE users SET referred_by_id = 1 WHERE id IN (2, 3);
UPDATE users SET referred_by_id = 2 WHERE id = 4;
-- SELF JOIN
SELECT A.ID,A.NAME AS USERNAME,B.NAME AS REF_BY FROM USERS A INNER JOIN USERS B ON A.REFERRED_BY_ID=B.ID; 